version: '3.8'

services:
  # Next.js application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jewelry-shop-nextjs
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APP_NAME=Zakarian
      - NEXT_PUBLIC_BACKEND_URL=http://backend/api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx service
  nginx:
    image: nginx:stable-alpine
    container_name: jewelry-shop-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
      - nginx-logs:/var/log/nginx
      # Uncomment the following lines if you have SSL certificates
      # - ./ssl/certs:/etc/nginx/ssl/certs:ro
      # - ./ssl/private:/etc/nginx/ssl/private:ro
    depends_on:
      - nextjs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs: